继续创

diff --git a/qzsec/access-client/access-client b/qzsec/access-client/access-client
--- a/qzsec/access-client/access-client
+++ b/qzsec/access-client/access-client
@@ -2,6 +2,19 @@
 
 URL="$1"
 
+if [ "$URL" == "" ]; then
+    echo "Usage: $0 accessclient://<args>"
+    sleep 5
+    exit 1
+fi
+
+if [ ! "$URL" == "accessclient://"* ]; then
+    echo "Invalid URL, should be accessclient://"
+    sleep 5
+    exit 1
+fi
+
+
 ARGS=$(echo $URL | sed 's|accessclient://||' | base64 -d | minideflate -d )
 
 APP=$(echo $ARGS | jq -r.app)
